### ISSUE TITLE
Creative Commons License?

### ISSUE THREAD

**Issue by ChristopherKing42** [BTCfork/btcforksite#5]
Although I like the sentiment, saying "Never copyright", it doesn't mean much legally. It would probably be more meaningful and more professional to use a [creative commons license](https://creativecommons.org/licenses/), such as CC BY, CC BY-SA, or [CC0](https://creativecommons.org/publicdomain/).

If you think this a good idea, name a license and I can make the pull request.

Maybe it isn't worth the bother though. I don't expect any legal battles over the copyright of the website (_trademark on the other hand_).

**Comment by keepcalmandfork** [comment]
Feel free to go through the CC0 process and make a PR.  I would keep the never copyright, perhaps add badging under or in place of the fork me text in the footer (and remove that anyway if we are doing the badge).  Thanks!
